"""create catalog schema

Revision ID: 6579b05df670
Revises: 
Create Date: 2026-07-20 00:44:42.106776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6579b05df670'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('slug', name=op.f('uq_brands_slug'))
    )
    op.create_table('models',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('model_year', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_models_brand_id_brands')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models')),
    sa.UniqueConstraint('brand_id', 'slug', name=op.f('uq_models_brand_id_slug'))
    )
    op.create_table('colors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('manufacturer_code', sa.String(length=16), nullable=True),
    sa.Column('finish_type', sa.Enum('solid', 'metallic', 'pearlescent', name='color_finish'), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_colors_model_id_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colors'))
    )
    op.create_table('option_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.Enum('equipment', 'package', 'warranty', 'service', name='option_category'), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_option_items_model_id_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_option_items'))
    )
    op.create_table('powertrains',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('manufacturer_code', sa.String(length=32), nullable=True),
    sa.Column('fuel_type', sa.Enum('petrol', 'diesel', 'mild_hybrid', 'phev', 'electric', name='fuel_type'), nullable=False),
    sa.Column('transmission', sa.String(length=64), nullable=True),
    sa.Column('drivetrain', sa.Enum('fwd', 'rwd', 'awd', name='drivetrain'), nullable=False),
    sa.Column('displacement_cc', sa.Integer(), nullable=True),
    sa.Column('cylinder_count', sa.SmallInteger(), nullable=True),
    sa.Column('power_kw', sa.Integer(), nullable=True),
    sa.Column('power_hp', sa.Integer(), nullable=True),
    sa.Column('torque_nm', sa.Integer(), nullable=True),
    sa.Column('top_speed_kmh', sa.Integer(), nullable=True),
    sa.Column('accel_0_100_s', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('consumption_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('consumption_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('consumption_unit', sa.Enum('l_100km', 'kwh_100km', name='consumption_unit'), nullable=True),
    sa.Column('co2_min_g_km', sa.Integer(), nullable=True),
    sa.Column('co2_max_g_km', sa.Integer(), nullable=True),
    sa.Column('emission_standard', sa.String(length=16), nullable=True),
    sa.Column('fuel_tank_l', sa.Integer(), nullable=True),
    sa.CheckConstraint('co2_max_g_km IS NULL OR co2_min_g_km IS NULL OR co2_max_g_km >= co2_min_g_km', name=op.f('ck_powertrains_co2_max_gte_min')),
    sa.CheckConstraint('consumption_max IS NULL OR consumption_min IS NULL OR consumption_max >= consumption_min', name=op.f('ck_powertrains_consumption_max_gte_min')),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_powertrains_model_id_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_powertrains'))
    )
    op.create_table('source_documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Enum('price_list', 'brochure', name='document_type'), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('campaign_valid_from', sa.Date(), nullable=True),
    sa.Column('campaign_valid_to', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_source_documents_model_id_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_documents'))
    )
    op.create_table('trims',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_trims_model_id_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trims')),
    sa.UniqueConstraint('model_id', 'name', name=op.f('uq_trims_model_id_name'))
    )
    op.create_table('configurations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trim_id', sa.BigInteger(), nullable=False),
    sa.Column('powertrain_id', sa.BigInteger(), nullable=False),
    sa.Column('manufacturer_code', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['powertrain_id'], ['powertrains.id'], name=op.f('fk_configurations_powertrain_id_powertrains')),
    sa.ForeignKeyConstraint(['trim_id'], ['trims.id'], name=op.f('fk_configurations_trim_id_trims')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configurations')),
    sa.UniqueConstraint('trim_id', 'powertrain_id', name=op.f('uq_configurations_trim_id_powertrain_id'))
    )
    op.create_table('configuration_colors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('configuration_id', sa.BigInteger(), nullable=False),
    sa.Column('color_id', sa.BigInteger(), nullable=False),
    sa.Column('surcharge_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name=op.f('fk_configuration_colors_color_id_colors')),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], name=op.f('fk_configuration_colors_configuration_id_configurations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration_colors')),
    sa.UniqueConstraint('configuration_id', 'color_id', name=op.f('uq_configuration_colors_configuration_id_color_id'))
    )
    op.create_table('option_availability',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('option_item_id', sa.BigInteger(), nullable=False),
    sa.Column('configuration_id', sa.BigInteger(), nullable=False),
    sa.Column('availability', sa.Enum('standard', 'optional', 'unavailable', name='availability_status'), nullable=False),
    sa.Column('surcharge_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), nullable=True),
    sa.CheckConstraint("(availability = 'optional') = (surcharge_amount IS NOT NULL)", name=op.f('ck_option_availability_surcharge_set_iff_optional')),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], name=op.f('fk_option_availability_configuration_id_configurations')),
    sa.ForeignKeyConstraint(['option_item_id'], ['option_items.id'], name=op.f('fk_option_availability_option_item_id_option_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_option_availability')),
    sa.UniqueConstraint('option_item_id', 'configuration_id', name=op.f('uq_option_availability_option_item_id_configuration_id'))
    )
    op.create_table('prices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('configuration_id', sa.BigInteger(), nullable=False),
    sa.Column('source_document_id', sa.BigInteger(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('list_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_incl_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_excl_vat', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('lowest_price_30d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name=op.f('ck_prices_valid_to_after_valid_from')),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], name=op.f('fk_prices_configuration_id_configurations')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_prices_source_document_id_source_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prices'))
    )
    op.create_index('uq_prices_current_per_configuration_market', 'prices', ['configuration_id', 'market'], unique=True, postgresql_where='valid_to IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_prices_current_per_configuration_market', table_name='prices', postgresql_where='valid_to IS NULL')
    op.drop_table('prices')
    op.drop_table('option_availability')
    op.drop_table('configuration_colors')
    op.drop_table('configurations')
    op.drop_table('trims')
    op.drop_table('source_documents')
    op.drop_table('powertrains')
    op.drop_table('option_items')
    op.drop_table('colors')
    op.drop_table('models')
    op.drop_table('brands')
    # ### end Alembic commands ###

    # Autogenerate creates Postgres native enum types implicitly (via the
    # first column that uses them) but never emits DROP TYPE on downgrade -
    # without this, a downgrade-then-upgrade round trip fails with
    # "type already exists".
    for enum_name in (
        "availability_status",
        "option_category",
        "document_type",
        "consumption_unit",
        "drivetrain",
        "fuel_type",
        "color_finish",
    ):
        op.execute(f"DROP TYPE {enum_name}")
